ATR-401: practice dsl resolver
useheartbeat/heartbeat-practice pull request #1
Opened 2022-05-09 19:39 UTC by rasanjalee-dissanayaka

2022-05-10 03:47 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/HeartbeatPracticeApplication.kt
>  import org.springframework.boot.autoconfigure.EnableAutoConfiguration
This configuration is redundant, and remove @EnableAutoConfiguration at line 29

2022-05-10 03:48 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/HeartbeatPracticeApplication.kt
>      @Autowired lateinit var practiceService: PracticeService
These two variable never used, and can be removed.

2022-05-10 03:49 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/HeartbeatPracticeApplication.kt
> +            var response = message.let { graphQLProvider.executeQuery(it)}
This should val.

2022-05-10 03:50 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/Utils/Utils.kt
>  import com.heartbeathealth.notification.shim.NotificationService
Few unused imports can be removed.

2022-05-10 03:51 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/Utils/Request.kt
>  package com.heartbeat.practice.heartbeatpractice.Utils
Package name should not start with capital.

2022-05-10 03:52 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/Utils/Utils.kt
>  fun String.toUUID() : UUID {
This and toUUIDList never used, and can be removed.

2022-05-10 03:52 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/Utils/Utils.kt
> +inline fun <reified T> Map<String, Any>.toDataClass(): T {
This function never used.

2022-05-10 03:54 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
> +    lateinit var notificationService: NotificationService
Never used, can be removed.

2022-05-10 03:55 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
>      fun isHeartbeatPractice(practiceId: UUID) =
remove this function

2022-05-10 03:57 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
>      private suspend fun withPracticeAdminIds(practiceId: UUID, closure: suspend (List<UUID>) -> Unit) {
remove

2022-05-10 03:57 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
> +    suspend fun getPracticeAffiliationsSync(
remove

2022-05-10 03:57 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
> +    suspend fun getPatientPracticeIds(patientId: UUID): List<UUID> =
remove

2022-05-10 03:57 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
> +    suspend fun haveCommonPractices(providerId: UUID, patientId: UUID) =
remove

2022-05-10 03:58 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
>      suspend fun getCommonProviderPracticeIds(providerId1: UUID, providerId2: UUID): List<UUID> =
remove

2022-05-10 03:59 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
> +    suspend fun isProviderAffiliatedToPractice(providerId: UUID, practiceId: UUID): Boolean =
remove

2022-05-10 03:59 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
> +    suspend fun isProviderAffiliatedToPracticeAsAnyOf(
remove

2022-05-10 03:59 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
>      suspend fun getAffiliatedProviderIds(practiceId: UUID, onlyVerified: Boolean = true, onlyRole: PracticeRole?) =
remove

2022-05-10 04:00 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
remove removeSupportedUserTags function

2022-05-10 04:00 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/service/PracticeService.kt
> +    private suspend fun <T> withRegistrations(
remove

2022-05-10 04:02 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/graphql/PracticeDSLResolver.kt
> +import com.heartbeathealth.support.model.emptyConnection
remove this import

2022-05-10 04:03 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/graphql/PracticeDSLResolver.kt
> +import kotlinx.coroutines.future.asCompletableFuture
unused import

2022-05-10 04:09 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/graphql/PracticeDSLResolver.kt
> +                search?.let { search ->
name shadowed. You can rename second search in { } with different name, searchSpec

2022-05-10 04:10 UTC, benleehealth commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/model/Practice.kt
> +import java.time.OffsetDateTime
unused import

2022-05-10 04:20 UTC, benleehealth requested changes
Assuming this is not live code, looks good to me. All comments are cosmetic.

2022-05-12 12:54 UTC, rasanjalee-dissanayaka commented on src/main/kotlin/com/heartbeat/practice/heartbeatpractice/model/Practice.kt
> +import java.time.OffsetDateTime
all addressed

2022-05-16 18:45 UTC, merged